language: php
php:
- 7.4.3
cache:
  directories:
  - "$HOME/.composer/cache"
jobs:
  fast_finish: true
before_script:
- composer install
script:
- php vendor/bin/phplint
- php vendor/bin/phpspec run
- php vendor/bin/phpunit --prepend "./tests/unit/xdebug-filter.php"
- php vendor/bin/infection --debug -j2 --filter=src --coverage=build/coverage/phpunit/
  --min-covered-msi=94 --min-msi=94 --test-framework=phpunit
- php vendor/bin/phpcs --runtime-set ignore_warnings_on_exit true --cache -p src
  tests
after_success:
- travis_retry bash <(curl -s https://codecov.io/bash) -s build/coverage/phpunit -s build/coverage/phpspec/phpspec-coverage-xml
- travis_retry php vendor/bin/php-coveralls
